"""Add relationships

Revision ID: 06ce942574fb
Revises: 7fd88b70e08d
Create Date: 2025-05-26 10:05:29.460592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ce942574fb'
down_revision = '7fd88b70e08d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
