"""Create dev, company, and freebie tables

Revision ID: 79f491ad095c
Revises: 06ce942574fb
Create Date: 2025-05-26 10:59:38.889614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f491ad095c'
down_revision = '06ce942574fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
